### ISSUE TITLE
Collapse component on Demo page will stop to functioning after several clicks using chrome

### ISSUE THREAD

**Issue by chenull** [thednp/bootstrap.native#115]
In chrome Version 56.0.2924.87 (64-bit), the [Collapse Component on demo page](http://thednp.github.io/bootstrap.native/#collapseExamples) will stop functioning after some number of clicks. sometimes a few clicks, sometimes a lot. The corresponding JS log `The show/hidden.bs.collapse event fired` is stopped too. After i cloned this repo and checkout to `gh-pages`, and trying to reverting/bisect commits, i found this issue started after `` 369c3ea... Replaced `duration`  option with `transitionEnd` ``. The commit before that, which is `` e4dbfaf... Removed isIE detection utility from V4 `` is ok. I can click the collapse action many many times

**Note**: This doesn't happen in Safari

**Comment by thednp** [comment]
Does this happen after the last commit? https://github.com/thednp/bootstrap.native/commit/0e7aa35543298461119c2899f049284bb9d7844d

**Comment by thednp** [comment]
@chenull ?

**Comment by chenull** [comment]
Hi, i git pulled the last commit, fire up simple http server, do the clicks from chrome, and whenever the collapse stop working, i copy-pasted logs from JS console and here the result:

```shell
for log in clicks-*; do echo -n $log; cat $log | wc -l; done
clicks-01      88
clicks-02     124
clicks-03      92
clicks-04       3
clicks-05     147
clicks-06     379
clicks-07      19
clicks-08       3
clicks-09     115
clicks-10      15
```

so yes, it still happen, though it takes longer to be happen than my first time i visit your demo page. only happen twice with 3 clicks. it was happen quicker before.

**Comment by thednp** [comment]
Cannot reproduce, the demo works properly for me, but I suspect why it happens on your end.

**Comment by chenull** [comment]
yeah, me too, it's hard to reproduce after your last commit. but i managed to create a gif animation when this happen

![raisoclick-export](https://cloud.githubusercontent.com/assets/1737556/23052857/458833e2-f507-11e6-8f0e-2c5b76029892.gif)

https://cloud.githubusercontent.com/assets/1737556/23052857/458833e2-f507-11e6-8f0e-2c5b76029892.gif

**Comment by chenull** [comment]
oh.. one more thing to note that, when it stopped working. the current collapsed item (the lorem ipsum text) is **always** in hidden condition. then next click, which should be the `show` event, is not happening.

**Comment by thednp** [comment]
@chenull please confirm this test for the tabs example, it involves a similar isssue I hope I fixed.

**Comment by thednp** [comment]
@chenull are you in Linux? On my Windows 8.1 with Google Chrome, Firefox and IE10 everything works perfect, I am now typing from Ubuntu, and I confirm the issue persists.

I believe this must be related to the fact that Linux is a bit slower executing some nested `setTimeout` functions and it gets stuck somewhere, but I am now working with Linux and working on a fix to make it full proof.

**Comment by thednp** [comment]
I think I fixed the issue, I will do some tests in Windows with IE10 and commit asap.

**Comment by thednp** [comment]
@chenull 
Please test the latest commit ASAP. I will release a new tag once you confirm the issues to be fixed.

**Comment by chenull** [comment]
@thednp yeah it fixed 👍 i am on a mac though, not linux

**Comment by thednp** [comment]
> @thednp yeah it fixed 👍 i am on a mac though, not linux

Same for me.. OK thanks for the confirm.

**Comment by chenjau** [comment]
After testing with hundreds of click,  [demo page](http://thednp.github.io/bootstrap.native/#collapseExamples)  I think this bug still exist in firefox.
