### ISSUE TITLE
Classes Applied At Incorrect Times In V3 Collapse

### ISSUE THREAD

**Issue by Ixonal** [thednp/bootstrap.native#156]
It looks like a few of the classes in the V3 Collapse open and close actions are added/removed at slightly different times from the regular Bootstrap implementation. This has the effect of showing the scroll bar durring the opening/closing animation. 

The current bsn implementation of the open action immediately adds the "collapsing" and "in" classes immediately, then removes the "collapsing" class after transition end. The V3 Bootstrap code adds the "collapsing" class and removes both "collapse" and "in" classes immediately, then adds "collapse" and removes "collapsing" classes after transition end. Similarly, the close action for bsn adds the "collapsing" class (after a very short timeout), then removes the "collapsing" and "in" classes after transition end. The V3 Bootstrap hide function immediately adds the "collapsing" class and removes the "collapse" and "in" classes, then removes the "collapsing" and adds the "collapse" classes after transition end.

I made changes to my local copy, rearranging the adding and removing of classes to match the order in the regular Bootstrap code, and it worked as expected.

I'm not sure about the V4 version, since I'm not currently using it.

Using version 2.0.14
Code in Question: 
https://github.com/thednp/bootstrap.native/blob/master/lib/V3/collapse-native.js

**Comment by thednp** [comment]
Please make a fork and apply your changes, I can have a look as soon as I can.
Thanks

**Comment by Ixonal** [comment]
Will do after I get off work.

**Comment by Ixonal** [comment]
https://github.com/Ixonal/bootstrap.native/blob/master/lib/V3/collapse-native.js
Pretty simple changes there. Still need to put together a fiddle or some such to test it, but thought I'd let you take a look.

**Comment by thednp** [comment]
A quick note of a reminder, our goal here is not to perfectly transpose the jQuery code into native JavaScript, but to have same functionality in a very stable and reliable code.

**Comment by thednp** [comment]
I checked your code and tested on my machine and seems to be fine, strange it works in that order, but if the original script works this way we'll use it this way then. I will prepare commits asap.

**Comment by Ixonal** [comment]
> our goal here is not to perfectly transpose the jQuery code into native JavaScript

Right right, which is why I used your existing functions to accomplish the task. Not really a change of infrastructure, just order of operations.

> strange it works in that order

Well, the main issue is the "in" class, as that applies "overflow-y: auto" just in case, for example, a navbar is too long. The "collapsing" class applies "overflow-y: hidden". So you want to hide the overflow until the animation is over, then show any necessary scrollbar for it.

**Comment by thednp** [comment]
Right.

**Comment by Ixonal** [comment]
Tested the current master code and there's a short flash of the scroll bar being there on close (open seems ok). I think it's due to doing it after that 20ms timeout. There a particular reason that's there?

**Comment by thednp** [comment]
I just fixed that, got rid of the `setTimeout` as well, will now look into fixing the Tab to work properly as well.

**Comment by thednp** [comment]
Hmm with tabs is a bit tricky, the display messes up things big time.

**Comment by Ixonal** [comment]
Can show an element, get its height, and then hide it again. As long as there's no timeout, it happens too fast to render to the screen, but the box model is calculated. Don't want to do it a lot, but fine if you're just doing it once like this.

**Comment by thednp** [comment]
Please try this latest one, I think I nailed it. I figured the `clickHandler` didn't filter out properly.

**Comment by Ixonal** [comment]
Sorry about the latency of my reply. Just got in and tested it out. Noticed it's still showing the scroll bar when collapsing the navbar (though, opening it works properly). Looks like I may have borked earlier when I said the "in" class is removed after the transition end; the Bootstrap code shows it being removed before the transition.
[https://github.com/twbs/bootstrap/blob/master/js/collapse.js#L110](url)
Simple fix, at least.

**Comment by thednp** [comment]
@Ixonal if you would change the current code to be on par with the original jQuery plugin, would it work as you would expect? If yes, please let me know what changes we should make. Thanks

**Comment by Ixonal** [comment]
https://github.com/thednp/bootstrap.native/blob/master/lib/V3/collapse-native.js
The change should be as simple as moving line 57 up under line 47.

**Comment by thednp** [comment]
That's simple indeed, but does it work 100% as you would expect it to?

**Comment by Ixonal** [comment]
Well, as far as I'm reading, it's what Bootstrap is doing. I linked the code earlier, so you can take a peek to make sure I'm not missing something.

**Comment by thednp** [comment]
It seems to work fine, no more scrollbar for the navbar on close. How do you like the new demo and [wiki pages](https://github.com/thednp/bootstrap.native/wiki)?

**Comment by Ixonal** [comment]
https://gist.run/?id=6b26c82ad118399aa3e8d8406b634800
That gist is showing a scroll bar in the navbar when collapsing for me.

I've been a bit leery of wiki pages. It's been my experience that nobody adds to or modifies them :/

**Comment by thednp** [comment]
Yea, so the reason why this happens is this:

```css
.navbar-collapse.in {
    overflow-y: auto;
}
````

To my understanding, the navbar is supposed to be accessible for mobile devices no matter how many menu items it has, the above CSS makes sure of that, but it also makes it have a scrollbar on closing the collapse element.

**Comment by Ixonal** [comment]
Exactly. You want it there when the nav is open so that the user can scroll if needed, but not while the open/close animation is happening. The user isn't going to be scrolling in the navigation while opening/closing it. So for opening, you add it after the animation has finished, and for closing, remove it immediately before the animation.

**Comment by thednp** [comment]
Sorry I forgot to make this change before the 2.0.15 tag release, will have it in the next. Next on my list is the [popper functionality](https://github.com/thednp/bootstrap.native/issues/158).

**Comment by Ixonal** [comment]
It's all good, it's not a major issue, so I'm not terribly worried.
